coding_task:
  description: >
   {topic}. Always use the DirectoryTool to find info.md and then read it usingFileReader tool.NOTE file name is info.md
  expected_output: >
    code executed correctly with the expected output mentioned in the decription.
  agent: Coder

  